; Code located in the slow memory

    INCLUDE "Utils/_index.asm"
    INCLUDE "Menu/_index.asm"
    INCLUDE "Panel/_index.asm"
    INCLUDE "Control/control.asm"
    INCLUDE "orig/code/Location/moveToMapSpan.asm"
    INCLUDE "orig/code/Location/advanceInMap.asm"
    INCLUDE "orig/code/Location/advanceObjectsInMap.asm"
    INCLUDE "orig/code/Location/startPositions.asm"
    INCLUDE "orig/code/Location/transit.asm"
    INCLUDE "orig/code/Location/shop.asm"
    INCLUDE "orig/code/Tiles/tiles.asm"
    INCLUDE "orig/code/Tiles/conveyorTileIndices.asm"
    INCLUDE "orig/code/Tiles/conveyors.asm"
    INCLUDE "orig/code/Tiles/rollConveyorTiles.asm"
    INCLUDE "orig/code/Scene/clearScene.asm"
    INCLUDE "orig/code/Scene/visibility.asm"
    INCLUDE "orig/code/Scene/cleanUpScene.asm"
    INCLUDE "Hero/_slow.asm"
    INCLUDE "Enemy/_slow.asm"
    INCLUDE "Boss/switch.asm"
    INCLUDE "Sound/sound.asm"
