    INCLUDE "mainMenu.asm"
    INCLUDE "orig/code/Menu/levelSelectMenu.asm"
    INCLUDE "orig/code/Menu/levelLoading.asm"
    INCLUDE "orig/code/Menu/gameOver.asm"
    INCLUDE "orig/code/Menu/gameWin.asm"
    INCLUDE "orig/code/Menu/pause.asm"
