; This file is generated by the `build_assets` script
    MODULE Lev3Iceland


; #6C00
tilePixels:
        dh 00 00 00 00 00 00 00 00 ; tile #00 (bg space)
        dh 00 00 07 0F 1F 1E 1D 3A ; tile #01 (bg space)
        dh 00 F8 F4 EE F2 E9 F3 D7 ; tile #02 (bg space)
        dh 00 03 07 07 0F 0F 0F 0F ; tile #03 (bg space)
        dh FF FF FF FF DF AF DE ED ; tile #04 (bg space)
        dh EC D0 B0 D8 A9 DC BE 5F ; tile #05 (bg space)
        dh 80 40 60 A0 10 90 28 84 ; tile #06 (bg space)
        dh 0F 1F 1F 1F 1F 1E 3D 3E ; tile #07 (bg space)
        dh DA B6 C2 A0 42 80 40 40 ; tile #08 (bg space)
        dh 0D 0D 0A 06 04 04 00 00 ; tile #09 (bg space)
        dh 94 8C D4 D0 44 68 68 64 ; tile #0A (bg space)
        dh 3D 1E 3F 3E 7F 7E FD FA ; tile #0B (bg space)
        dh 40 00 00 00 00 80 50 AB ; tile #0C (bg space)
        dh 00 00 00 00 01 02 0D FF ; tile #0D (bg space)
        dh 2C 6A 54 AA F5 FE FD FA ; tile #0E (bg space)
        dh 7F FF F7 FB D7 EF A5 C2 ; tile #0F (fg wall)
        dh FE FF DF A7 C2 A5 41 05 ; tile #10 (fg wall)
        dh C0 40 80 C0 40 85 80 7F ; tile #11 (fg wall)
        dh 05 0D 0D 1D 7D F9 03 FE ; tile #12 (fg wall)
        dh 2A 5D 3E 7D FE 7D EA 75 ; tile #13 (fg wall)
        dh 0A 1F 9E 1D 8A 15 8A 40 ; tile #14 (fg wall)
        dh 8A D4 88 41 8B 17 0E 5D ; tile #15 (fg wall)
        dh 00 10 F8 FC E8 F4 A8 74 ; tile #16 (fg wall)
        dh 2A 55 2F 1F 2E 15 8A C5 ; tile #17 (fg wall)
        dh A2 51 AA 50 A8 51 A3 05 ; tile #18 (fg wall)
        dh 8F 5D 8F 5F 0E 0F 8B 47 ; tile #19 (fg wall)
        dh AA 54 AA 5C BA 54 A8 51 ; tile #1A (fg wall)
        dh A2 40 8A 17 3F 5F 3E 77 ; tile #1B (fg wall)
        dh 0E 1D 8A 45 E2 D4 E0 50 ; tile #1C (fg wall)
        dh AA 45 80 54 8A 1F 3E 1D ; tile #1D (fg wall)
        dh EB 51 A8 54 2A 35 AA 15 ; tile #1E (fg wall)
        dh 2E 75 2E 15 2A 15 0A 01 ; tile #1F (fg wall)
        dh A0 51 A2 51 A3 57 86 05 ; tile #20 (fg wall)
        dh 3A 15 8A D5 EA 44 A0 45 ; tile #21 (fg wall)
        dh BA 34 AA 14 2A 74 28 00 ; tile #22 (fg wall)
        dh FF FD FF FA 54 80 60 78 ; tile #23 (fg wall)
        dh FF FF F7 FC BE 5D 3A 00 ; tile #24 (fg wall)
        dh FF FB E7 1F BF 3D 1A 00 ; tile #25 (fg wall)
        dh FF FF FF DF EF 95 0A 00 ; tile #26 (fg wall)
        dh 2A 45 2F 1F 2E 15 8A C5 ; tile #27 (fg wall)
        dh 80 51 AA 50 A8 51 A3 05 ; tile #28 (fg wall)
        dh 02 15 8A 5D 0E 0F 8B 47 ; tile #29 (fg wall)
        dh 28 54 AA 5C BA 54 A8 51 ; tile #2A (fg wall)
        dh 00 00 00 00 00 03 2F FF ; tile #2B (bg space)
        dh 00 00 00 00 00 E8 F5 6A ; tile #2C (bg space)
        dh 00 00 00 00 00 00 0E FF ; tile #2D (bg space)
        dh 00 00 00 00 00 00 A0 D5 ; tile #2E (bg space)
        dh 00 00 00 00 00 18 7E FC ; tile #2F (bg space)
        dh FB F7 ED E9 D2 DC 40 40 ; tile #30 (bg wall)
        dh DA F7 00 FF 00 00 00 00 ; tile #31 (bg wall)
        dh DD BD 18 CF 18 00 08 00 ; tile #32 (bg wall)
        dh DA F7 00 FF 00 7E 7D 33 ; tile #33 (bg ladder top)
        dh DD BD 18 CF 18 00 48 44 ; tile #34 (bg ladder top)
        dh 00 00 0F 3E 7F 7F 7F 7F ; tile #35 (bg platform)
        dh 07 1F 3F DF BF FF FF FF ; tile #36 (bg platform)
        dh C0 F0 ED FA FE FD FF FF ; tile #37 (bg platform)
        dh 3F FF FF BF 7F FF FF FF ; tile #38 (bg platform)
        dh 00 C0 A0 D0 AE DF FF FF ; tile #39 (bg platform)
        dh 3F 3F 1B 04 01 00 00 00 ; tile #3A (bg space)
        dh DF EF 5F BF 7F AF 55 0A ; tile #3B (bg space)
        dh BF EF D1 E8 D4 A9 40 00 ; tile #3C (bg space)
        dh FF FF FF 5F BE 55 A8 00 ; tile #3D (bg space)
        dh FF FD E3 F6 A8 00 00 00 ; tile #3E (bg space)
        dh E8 F4 FA F4 FA F4 EA 74 ; tile #3F (fg ice)
        dh BA 74 28 74 28 04 20 04 ; tile #40 (fg space)
        dh 2F 5F 3F 7F FE 7D FA F5 ; tile #41 (fg ice)
        dh BA 7D BA 1D BA 10 2A 10 ; tile #42 (fg space)
        dh 2A 5D 3E 7D FE 7D EA 75 ; tile #43 (fg ice)
        dh 2A 55 2F 1F 2E 15 0A 05 ; tile #44 (fg ice)
        dh 02 00 0A 17 3F 5F 3E 77 ; tile #45 (fg ice)
        dh 2E 75 2E 15 2A 15 0A 01 ; tile #46 (fg ice)
        dh 00 10 F8 FC E8 F4 A8 74 ; tile #47 (fg ice)
        dh AA 54 AA 5C BA 54 A8 50 ; tile #48 (fg ice)
        dh E8 50 A8 54 2A 75 AA 15 ; tile #49 (fg ice)
        dh BA 34 AA 14 2A 74 28 00 ; tile #4A (fg ice)
        dh 01 01 01 01 0F 00 01 01 ; tile #4B (bg space)
        dh FF 70 60 60 FF C0 BB FF ; tile #4C (bg space)
        dh 80 80 80 80 F0 00 80 80 ; tile #4D (bg space)
        dh 01 0D 3F 77 7F 5F 7D 3D ; tile #4E (bg space)
        dh FF BB EF 7C E1 FA FF FF ; tile #4F (bg space)
        dh 80 80 00 60 50 A8 B8 B4 ; tile #50 (bg space)
        dh 3F 3F 3F 1F 1F 1F 16 09 ; tile #51 (bg space)
        dh FF FF FF 7E 6E FE FF FF ; tile #52 (bg space)
        dh 7C FC F8 E8 F8 E8 50 A0 ; tile #53 (bg space)
        dh 0F 0F 1F 1F 3B 7D FF F7 ; tile #54 (bg space)
        dh AE DD E3 F7 F7 DB B5 55 ; tile #55 (bg space)
        dh F0 E0 F0 F0 88 34 EA 55 ; tile #56 (bg space)
        dh 08 08 08 08 08 08 08 18 ; tile #57 (bg water/spikes)
        dh 18 10 18 18 18 10 18 18 ; tile #58 (bg wall)
        dh 3C 3C 34 38 3C 38 34 3C ; tile #59 (bg wall)
        dh 34 38 3C 3A 3E 3A 3C 76 ; tile #5A (bg wall)
        dh 3C 34 3C 34 38 FC FA F5 ; tile #5B (bg wall)
        dh 00 07 0E 1F 1F 1F 0F 1F ; tile #5C (bg space)
        dh 00 80 E0 B0 EF FF FF FE ; tile #5D (bg space)
        dh 00 00 00 00 C0 B0 58 A8 ; tile #5E (bg space)
        dh 00 08 08 0C 1C 1C 3E 3A ; tile #5F (bg space)
        dh 00 00 00 01 07 0F 0E 3F ; tile #60 (bg space)
        dh 7D FA FD FF FF FF FF FB ; tile #61 (bg space)
        dh 00 80 40 A0 E0 50 E8 D4 ; tile #62 (bg space)
        dh 00 00 01 07 0D 30 20 E1 ; tile #63 (bg space)
        dh 7B FC D4 98 18 31 67 DA ; tile #64 (bg space)
        dh 35 53 21 41 80 C0 FC FB ; tile #65 (bg space)
        dh FE 1B 0D 08 A8 04 00 00 ; tile #66 (bg space)
        dh 00 00 00 00 00 03 00 01 ; tile #67 (bg space)
        dh 00 01 07 1C F8 8C 7E E8 ; tile #68 (bg space)
        dh F0 BE 3F 7F 6F 56 E5 AF ; tile #69 (bg space)
        dh 54 B8 F0 D0 88 80 C4 A0 ; tile #6A (bg space)
        dh 06 84 04 0E 11 00 00 00 ; tile #6B (bg space)
        dh 80 00 00 00 00 00 00 00 ; tile #6C (bg space)
        dh 00 00 04 0C 08 00 01 07 ; tile #6D (bg space)
        dh 51 26 29 03 04 C0 A4 58 ; tile #6E (bg space)
        dh 58 88 10 16 7C E0 80 80 ; tile #6F (bg space)
        dh D0 F0 28 30 30 10 10 00 ; tile #70 (bg space)
        dh DA F7 00 FF 00 7E 7D 33 ; tile #71 (bg platform)
        dh DD BD 18 CF 18 00 48 44 ; tile #72 (bg platform)
        dh 00 00 55 00 00 00 00 00 ; tile #73 (bg space)
        dh FA 30 7D 30 FA 00 00 00 ; tile #74 (bg space)
        dh FA 30 7D 30 FA 00 00 00 ; tile #75 (bg space)
        dh FA 30 7D 30 FA 00 00 00 ; tile #76 (bg space)
        dh 00 00 00 00 00 00 00 00 ; tile #77 (bg space)
        dh 07 06 0C 08 10 10 00 00 ; tile #78 (bg space)
        dh 39 00 20 00 00 00 00 00 ; tile #79 (bg space)
        dh 00 00 00 00 03 07 0F 01 ; tile #7A (bg space)
        dh 00 07 3F EF EF DF DF 08 ; tile #7B (bg space)
        dh 00 D0 CE EB A5 D6 F5 00 ; tile #7C (bg space)
        dh 00 00 00 00 C0 A0 50 00 ; tile #7D (bg space)
        dh 1E 3E 3E 3F 7E 04 77 77 ; tile #7E (bg space)
        dh 7D FF FD FD FD 20 BD A6 ; tile #7F (bg space)
        dh F9 F5 FA FC FA 80 F7 F7 ; tile #80 (bg space)
        dh A8 54 A8 54 AA 00 C4 AA ; tile #81 (bg space)
        dh 77 77 76 02 7D 62 17 AF ; tile #82 (bg space)
        dh 43 41 81 81 80 D0 EA FF ; tile #83 (bg space)
        dh 7F 77 77 90 BD A3 9F 7F ; tile #84 (bg space)
        dh C4 AA C4 0A C4 B0 EC 5A ; tile #85 (bg space)
        dh 00 B7 FF DD 77 AA 55 00 ; tile #86 (bg space)
        dh 00 DA FF FF D7 AA 55 00 ; tile #87 (bg space)
        dh 00 00 00 00 00 00 00 00 ; tile #88 (bg space)
        dh 74 3A 6C 7A 34 7A 6C 7A ; tile #89 (fg space)
        dh 7C 7A 34 7A 74 3A 7C 3A ; tile #8A (fg space)
        dh 00 00 A2 54 AA 00 00 00 ; tile #8B (bg space)
        dh 00 00 A9 54 AA 00 00 00 ; tile #8C (bg space)
        dh 3C 7A FF ED F5 DD 6A 3C ; tile #8D (bg platform)
        dh 3C 7E F5 DB FD F5 62 3C ; tile #8E (bg platform)
        dh FF FE ED 31 47 AA 54 00 ; tile #8F (fg space)
        dh FB FE 69 97 C7 AA 51 00 ; tile #90 (fg space)
        dh 44 CE 6D 6B B2 78 50 38 ; tile #91 (fg space)
        dh FE D4 AA D4 00 28 30 28 ; tile #92 (fg wall)
        dh 00 05 27 1D 77 0A 00 00 ; tile #93 (bg space)
        dh 00 90 F2 FC D7 A8 00 00 ; tile #94 (bg space)
        dh 00 B6 FE DC 76 AA 50 00 ; tile #95 (bg space)
        dh 00 CA FF FF D7 A8 00 00 ; tile #96 (bg space)
        dh 00 FE FF F7 E0 0A 55 00 ; tile #97 (bg space)
        dh 00 5E FF 60 57 AA 55 00 ; tile #98 (bg space)
        dh FF FF FD FC EE FD D5 E1 ; tile #99 (bg platform)
        dh FF FF FF EF D6 08 30 34 ; tile #9A (bg platform)
        dh EF EF D3 AC 3F 30 D9 D8 ; tile #9B (bg platform)
        dh F7 F7 EA 9C FE DA DA C2 ; tile #9C (bg platform)
        dh A9 8D 4D FB FF 84 04 00 ; tile #9D (bg space)
        dh 34 34 8C FF FF 4F 37 3F ; tile #9E (bg space)
        dh 39 D9 D9 FF FF F0 E0 EC ; tile #9F (bg space)
        dh 1A 9A 9A FE FE 38 10 00 ; tile #A0 (bg space)
        dh 0F 0F 7F 1F 37 79 7C 3D ; tile #A1 (bg space)
        dh EC E8 FC F0 C0 00 00 00 ; tile #A2 (bg space)
        dh 30 78 C8 0C 04 04 3A FD ; tile #A3 (bg space)
        dh 00 00 60 31 19 10 2B 5F ; tile #A4 (bg space)
        dh 40 80 80 00 00 D0 EA F5 ; tile #A5 (bg space)
        dh 00 00 10 20 20 60 4A 7D ; tile #A6 (bg space)
        dh 9F 17 2E 5F 7B 3A 22 5C ; tile #A7 (bg ice)
        dh E7 0D 1B 17 1C 38 1D 00 ; tile #A8 (bg ice)
        dh 1F 06 8C 19 33 7D 8F 17 ; tile #A9 (bg ice)
        dh F8 16 EF DF BF 7E 9C 50 ; tile #AA (bg ice)
        dh 00 00 01 02 03 05 03 0B ; tile #AB (bg space)
        dh 40 80 80 80 60 C0 C0 B8 ; tile #AC (bg space)
        dh 1D 39 21 21 45 EE D8 91 ; tile #AD (bg space)
        dh 7C A8 14 BE CE 69 81 CE ; tile #AE (bg space)
        dh 00 00 01 03 03 02 02 04 ; tile #AF (bg space)
        dh 13 79 FE F7 C2 4C 07 0F ; tile #B0 (bg space)
        dh 9B 15 8C 3C 70 D8 C2 8F ; tile #B1 (bg space)
        dh 00 00 80 80 C0 20 20 80 ; tile #B2 (bg space)
        dh 07 07 0F 0F 0C 09 0F 0F ; tile #B3 (bg space)
        dh 5F D9 FB DF 53 F0 F9 EE ; tile #B4 (bg space)
        dh CF C3 5A 9B D8 CB CF 5F ; tile #B5 (bg space)
        dh A0 C0 E0 70 B0 C0 E0 F0 ; tile #B6 (bg space)
        dh 0C 18 17 1F 3F 3F 7C 70 ; tile #B7 (bg space)
        dh 6F 47 C1 C5 F0 F3 3A 1C ; tile #B8 (bg space)
        dh 78 B8 D3 D1 96 1F 7F 92 ; tile #B9 (bg space)
        dh 38 18 08 B8 30 98 E8 F0 ; tile #BA (bg space)
        dh 20 0F 3F 3F 7A 71 4F 7F ; tile #BB (bg space)
        dh 5F 7F 5F 7F 5F 7F 5F 7F ; tile #BC (bg wall)
        dh E2 52 E2 52 E2 52 E2 52 ; tile #BD (bg wall)
        dh 0C E5 F0 BC 1C 40 A8 55 ; tile #BE (bg space)
        dh 78 10 43 4F 91 40 43 2F ; tile #BF (bg space)
        dh F0 B8 9C 96 D6 C2 82 51 ; tile #C0 (bg space)
        dh 03 1F 3F 7F 7F 7F FF FF ; tile #C1 (fg wall)
        dh FF FF FF FF FF FF FF FF ; tile #C2 (fg wall)
        dh FF FF FF FF FF FF FF FF ; tile #C3 (fg wall)
        dh FF FB E7 FF FF FF FF FF ; tile #C4 (fg wall)
        dh C0 F8 FC FE FE FE FF FF ; tile #C5 (fg wall)
        dh FF FF B1 30 01 87 FF FF ; tile #C6 (fg wall)
        dh 40 60 78 7F FF FF FF FF ; tile #C7 (fg wall)
        dh 00 00 00 80 F0 FC FE FF ; tile #C8 (fg wall)
        dh 00 00 00 00 0F 3F 7F 7F ; tile #C9 (fg wall)
        dh 08 18 3C FC FC FE FE FE ; tile #CA (fg wall)
        dh 7F 7F 3F 3F 3F 1F 0F 0F ; tile #CB (fg wall)
        dh FF FF FF FF FF FF FF FF ; tile #CC (fg wall)
        dh 7F FF FF FF FF FF FF FF ; tile #CD (fg wall)
        dh FE FE FC FC F8 F0 E0 C0 ; tile #CE (fg wall)
        dh FF 1F 0F 07 03 03 07 0F ; tile #CF (fg wall)
        dh FF FC FE FE FE FE FF FF ; tile #D0 (fg wall)
        dh 38 70 20 00 82 10 00 04 ; tile #D1 (fg water/spikes)
        dh 00 10 00 80 04 00 00 20 ; tile #D2 (fg water/spikes)
        dh E8 9D BE 7D FE 7C 6A 74 ; tile #D3 (fg wall)
        dh AA D5 AF 9F CE C5 E8 F4 ; tile #D4 (fg wall)
        dh F0 F0 EA D7 BF 9F BE F7 ; tile #D5 (fg wall)
        dh AE F4 AE 95 8A D5 C2 E0 ; tile #D6 (fg wall)
        dh 03 13 F9 FD E9 F5 A9 75 ; tile #D7 (fg wall)
        dh A9 54 AA 5C B8 14 09 43 ; tile #D8 (fg wall)
        dh E3 53 A9 54 28 74 AA 15 ; tile #D9 (fg wall)
        dh 3A 34 2A 14 28 71 01 03 ; tile #DA (fg wall)
        dh 00 03 0F 1F 7F 7F FF FF ; tile #DB (bg ladder top)
        dh 00 C0 F0 F8 FC FC FE FE ; tile #DC (bg ladder top)
        dh FF FF FB 75 37 36 20 23 ; tile #DD (bg ladder)
        dh E4 EA 9C 78 70 C0 00 80 ; tile #DE (bg ladder)
        dh 07 07 02 07 07 07 02 07 ; tile #DF (bg ladder)
        dh A0 A0 00 A0 A0 A0 00 A0 ; tile #E0 (bg ladder)
        dh 07 07 07 0F 3F 7E 7D 33 ; tile #E1 (bg ladder)
        dh 7C F8 F0 E0 80 00 40 4C ; tile #E2 (bg ladder)
        dh 07 07 07 0F 3F 7E 7D 33 ; tile #E3 (bg space)
        dh 7C F8 F0 E0 80 00 40 4C ; tile #E4 (bg space)
        dh 55 FE DF FF EB 55 AA 00 ; tile #E5 (bg platform)
        dh 55 FF FF BF FB 55 AA 00 ; tile #E6 (bg platform)
        dh FF FF BF 1E DB 44 A4 00 ; tile #E7 (bg platform)
        dh 7F FF 55 A8 55 51 AA 00 ; tile #E8 (bg platform)
        dh E0 E0 E8 E4 AA E5 EB E7 ; tile #E9 (bg ladder)
        dh 07 07 0F 1F 3D 7F BF D7 ; tile #EA (bg ladder)
        dh E3 E5 EA E7 AA E4 E8 E0 ; tile #EB (bg ladder)
        dh A7 77 FF 7F 3D 1F 0F 07 ; tile #EC (bg ladder)
        dh F8 F1 EB 77 E3 55 A2 40 ; tile #ED (fg wall)
        dh 3F 1F 9E DD AA 45 82 00 ; tile #EE (fg wall)
        dh 07 07 07 07 07 03 03 03 ; tile #EF (bg space)
        dh 03 03 02 02 02 02 02 00 ; tile #F0 (bg space)
        dh 38 38 18 18 10 10 10 00 ; tile #F1 (bg space)
        dh FF D6 BF 40 52 4C FF FF ; tile #F2 (bg ladder top)
        dh FF FD BA 32 4A 32 FF FF ; tile #F3 (bg ladder top)
        dh 03 0F 1F 3F 3F 7F 73 77 ; tile #F4 (bg wall)
        dh E0 F8 FC FC EA C5 2A 05 ; tile #F5 (bg wall)
        dh 6A 47 2A 1C 2A 75 FE FF ; tile #F6 (bg wall)
        dh AA 05 BA 50 A0 14 AA FD ; tile #F7 (bg wall)
        dh FF FE FE 80 38 38 38 38 ; tile #F8 (bg ladder)
        dh 38 70 20 00 82 10 00 04 ; tile #F9 (bg ladder top)
        dh 00 10 00 80 04 00 00 20 ; tile #FA (bg space)
        dh FF FE FE 80 38 38 38 38 ; tile #FB (bg ladder top)
        dh 08 40 00 04 00 00 10 02 ; tile #FC (bg space)
        dh 00 08 80 00 02 10 00 00 ; tile #FD (bg space)
        dh C0 20 98 B0 E8 FC 54 38 ; tile #FE (fg ice)
        dh 00 05 1F 36 3F 6A 56 C4 ; tile #FF (fg ice)

; #7400
tileAttrs:
        dh 4F 4F 4F 4F 4F 4F 4F 4F 47 47 4F 4F 47 47 4F 4D ; tiles #0x
        dh 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D ; tiles #1x
        dh 4D 4D 4D 4F 4F 4F 4F 4D 4D 4D 4D 4F 4F 4F 4F 4F ; tiles #2x
        dh 4F 4F 4F 4F 4F 4F 4F 4F 4F 4F 4D 4D 4D 4D 4D 4F ; tiles #3x
        dh 4F 4F 4F 4D 4D 4D 4D 4D 4D 4D 4D 4F 4F 4F 4F 4F ; tiles #4x
        dh 4F 4F 4F 4F 4F 4F 4F 4F 4D 4D 4D 4D 4F 4F 4F 4F ; tiles #5x
        dh 4F 4F 4F 4D 4D 4D 4D 4D 4D 4F 4D 4F 4F 4F 4F 4F ; tiles #6x
        dh 4F 4F 4F 4F 4E 4E 4E 4F 4F 4F 4D 4F 4F 4D 4D 4F ; tiles #7x
        dh 4F 4D 4D 47 4F 4D 56 56 47 56 56 42 42 57 57 57 ; tiles #8x
        dh 57 56 56 56 56 56 56 57 57 4F 4F 4F 4F 4F 4F 4F ; tiles #9x
        dh 4F 4F 4F 4F 4F 4F 4F 4F 4F 4F 4F 4F 4C 4F 4C 4F ; tiles #Ax
        dh 4F 4C 4C 4F 4F 4C 4C 4F 4F 4C 4C 4F 4F 4F 4F 4C ; tiles #Bx
        dh 4C 48 48 48 78 48 78 48 48 48 48 48 48 48 48 48 ; tiles #Cx
        dh 48 4D 4D 4D 4D 4D 4D 4D 4D 4D 4D 4F 4F 4F 4F 4F ; tiles #Dx
        dh 4D 4F 4D 4F 4D 56 56 57 57 4D 4C 4D 4C 4D 4D 4D ; tiles #Ex
        dh 4F 4F 4F 4F 4F 4F 4F 4F 4F 4F 4F 4F 4D 4F 4F 4F ; tiles #Fx

; #7500
tileTypes:
        dh 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 84 ; tiles #0x
        dh 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 ; tiles #1x
        dh 84 84 84 84 84 84 84 84 84 84 84 00 00 00 00 00 ; tiles #2x
        dh 04 04 04 02 02 03 03 03 03 03 00 00 00 00 00 87 ; tiles #3x
        dh 80 87 80 87 87 87 87 87 87 87 87 00 00 00 00 00 ; tiles #4x
        dh 00 00 00 00 00 00 00 09 04 04 04 04 00 00 00 00 ; tiles #5x
        dh 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; tiles #6x
        dh 00 03 03 00 00 00 00 00 00 00 00 00 00 00 00 00 ; tiles #7x
        dh 00 00 00 00 00 00 00 00 00 80 80 00 00 03 03 80 ; tiles #8x
        dh 80 80 84 00 00 00 00 00 00 03 03 03 03 00 00 00 ; tiles #9x
        dh 00 00 00 00 00 00 00 07 07 07 07 00 00 00 00 00 ; tiles #Ax
        dh 00 00 00 00 00 00 00 00 00 00 00 00 04 04 00 00 ; tiles #Bx
        dh 00 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 ; tiles #Cx
        dh 84 89 89 84 84 84 84 84 84 84 84 02 02 01 01 01 ; tiles #Dx
        dh 01 01 01 00 00 03 03 03 03 01 01 01 01 84 84 00 ; tiles #Ex
        dh 00 00 02 02 04 04 04 04 01 02 00 02 00 00 87 87 ; tiles #Fx

; #7600
tileBlocks:
        dh 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; block #00
        dh 00 01 02 00 03 04 05 06 07 08 09 0A 0B 0C 0D 0E ; block #01
        dh 35 36 38 39 3A 3B 3C 3E 00 00 00 00 00 00 00 00 ; block #02
        dh 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F 20 21 22 ; block #03
        dh 00 00 00 41 00 00 00 42 00 00 00 00 2B 2C 2D 2E ; block #04
        dh 23 24 25 26 27 28 29 2A 1B 1C 1D 1E 1F 20 21 22 ; block #05
        dh 3F 00 00 00 40 00 00 00 00 00 00 00 2B 2C 2D 2E ; block #06
        dh 00 00 00 00 00 00 00 00 00 00 00 00 2B 2C 2D 2E ; block #07
        dh 4B 4C 4D 00 4E 4F 50 00 51 52 53 00 54 55 56 00 ; block #08
        dh 00 00 00 00 00 00 00 00 2F 00 00 00 30 31 32 31 ; block #09
        dh 00 00 00 00 00 00 00 00 00 00 00 00 32 32 31 32 ; block #0A
        dh 00 00 00 00 00 00 00 00 5C 5D 5E 00 54 55 56 00 ; block #0B
        dh 00 00 00 00 00 00 00 00 00 00 00 2F 32 31 32 30 ; block #0C
        dh D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 ; block #0D
        dh 43 14 15 16 44 18 19 1A 45 1C 1D 1E 46 20 21 22 ; block #0E
        dh 13 14 15 47 17 18 19 48 1B 1C 1D 49 1F 20 21 4A ; block #0F
        dh 43 14 15 47 44 18 19 48 45 1C 1D 49 46 20 21 4A ; block #10
        dh 23 24 25 26 44 28 29 2A 45 1C 1D 1E 46 20 21 22 ; block #11
        dh 23 24 25 26 27 28 29 48 1B 1C 1D 49 1F 20 21 4A ; block #12
        dh 23 24 25 26 44 28 29 48 45 1C 1D 49 46 20 21 4A ; block #13
        dh 2B 2C 2D 2E 23 24 25 26 1B 1C 1D 1E 1F 20 21 22 ; block #14
        dh 2B 2C 2D 2E 23 24 25 26 45 1C 1D 1E 46 20 21 22 ; block #15
        dh 2B 2C 2D 2E 23 24 25 26 1B 1C 1D 49 1F 20 21 4A ; block #16
        dh 3F 2C 2D 2E 23 24 25 26 1B 1C 1D 1E 1F 20 21 22 ; block #17
        dh 2B 2C 2D 41 23 24 25 26 1B 1C 1D 1E 1F 20 21 22 ; block #18
        dh 00 00 00 00 2B 2C 2D 2E 23 24 25 26 1F 20 21 22 ; block #19
        dh 00 00 00 00 2B 2C 2D 2E 23 24 25 26 46 20 21 22 ; block #1A
        dh 00 00 00 00 2B 2C 2D 2E 23 24 25 26 1F 20 21 4A ; block #1B
        dh 00 00 00 00 2B 2C 2D 2E 23 24 25 26 46 20 21 4A ; block #1C
        dh 00 00 00 00 3F 2C 2D 2E 23 24 25 26 1F 20 21 22 ; block #1D
        dh 00 00 00 00 2B 2C 2D 41 23 24 25 26 1F 20 21 22 ; block #1E
        dh 00 00 00 00 00 00 00 00 2B 2C 2D 2E 23 24 25 26 ; block #1F
        dh 00 00 00 00 00 00 00 00 3F 2C 2D 2E 23 24 25 26 ; block #20
        dh 00 00 00 00 00 00 00 00 2B 2C 2D 41 23 24 25 26 ; block #21
        dh 3F 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 ; block #22
        dh 00 00 00 41 00 00 00 42 00 00 00 00 00 00 00 00 ; block #23
        dh 00 57 00 00 57 58 00 57 58 59 57 58 5B 5A 5B 5A ; block #24
        dh 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; block #25
        dh 00 00 00 00 7A 7B 7C 7D 7E 7F 80 81 82 83 84 85 ; block #26
        dh 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; block #27
        dh 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 63 ; block #28
        dh 00 00 00 00 00 5F 00 00 60 61 62 00 64 65 66 00 ; block #29
        dh 00 67 68 69 00 6D 6E 6F 00 78 79 00 00 00 00 00 ; block #2A
        dh 6A 6B 6C 00 70 77 00 00 00 00 00 00 00 00 00 00 ; block #2B
        dh 86 87 86 87 87 86 87 86 86 87 86 87 87 86 87 86 ; block #2C
        dh 8F 91 8F 90 8C 89 8C 8B 86 8A 8B 87 92 92 92 92 ; block #2D
        dh 8F 91 8F 90 00 89 00 00 00 8A 00 00 92 92 92 92 ; block #2E
        dh 86 87 86 87 87 95 96 86 86 87 86 87 87 95 96 86 ; block #2F
        dh 00 00 00 8E 00 00 8D 93 00 8E 93 87 8D 93 87 86 ; block #30
        dh 8D 00 00 00 94 8E 00 00 86 94 8D 00 87 86 94 8E ; block #31
        dh 93 87 86 87 87 86 87 86 86 87 86 87 87 86 87 86 ; block #32
        dh 86 87 86 94 87 86 87 86 86 87 86 87 87 86 87 86 ; block #33
        dh 86 87 86 87 95 88 88 96 95 88 88 96 87 97 98 86 ; block #34
        dh 95 96 86 87 87 86 87 86 95 96 86 87 87 86 87 86 ; block #35
        dh 96 87 86 87 96 86 87 86 96 87 86 87 96 86 87 86 ; block #36
        dh 86 87 86 95 87 86 87 95 86 87 86 95 87 86 87 95 ; block #37
        dh 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 ; block #38
        dh C1 C2 C2 C4 C3 CC CC CC C3 CC CC CC C3 CC CC CC ; block #39
        dh C2 C2 C2 C2 CC CC CC CC CC CC CC CC C6 CC CC CC ; block #3A
        dh C2 C5 00 00 CC CC 00 00 CC CC 00 00 CC CC 00 00 ; block #3B
        dh 00 00 00 00 C7 C8 C9 CA CB CC CD CE 00 CF D0 00 ; block #3C
        dh A7 A8 A9 AA 27 28 29 2A 1B 1C 1D 1E 1F 20 21 22 ; block #3D
        dh A7 A8 A9 AA 44 28 29 2A 45 1C 1D 1E 46 20 21 22 ; block #3E
        dh A7 A8 A9 AA 27 28 29 48 1B 1C 1D 49 1F 20 21 4A ; block #3F
        dh D1 D1 D1 D1 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 D2 ; block #40
        dh 00 00 00 00 00 00 00 00 00 00 00 00 A3 A4 A5 A6 ; block #41
        dh 00 00 00 00 00 00 00 00 00 AB AC 00 00 AD AE 00 ; block #42
        dh AF B0 B1 B2 B3 B4 B5 B6 B7 B8 B9 BA BB BE BF C0 ; block #43
        dh 00 DB DC 00 00 DD DE 00 00 DF E0 00 00 E1 E2 00 ; block #44
        dh 99 9A 9B 9C 9D 9E 9F A0 00 A1 A2 00 32 71 72 32 ; block #45
        dh 00 E1 E2 00 00 E1 E2 00 00 E1 E2 00 00 E1 E2 00 ; block #46
        dh 73 73 73 73 00 00 00 00 00 00 00 00 00 00 00 00 ; block #47
        dh D3 14 15 16 D4 18 19 1A D5 1C 1D 1E D6 20 21 22 ; block #48
        dh 13 14 15 D7 17 18 19 D8 1B 1C 1D D9 1F 20 21 DA ; block #49
        dh D3 14 15 D7 D4 18 19 D8 D5 1C 1D D9 D6 20 21 DA ; block #4A
        dh D3 14 15 47 D4 18 19 48 D5 1C 1D 49 D6 20 21 4A ; block #4B
        dh 43 14 15 D7 44 18 19 D8 45 1C 1D D9 46 20 21 DA ; block #4C
        dh E5 E6 E5 E6 00 00 00 00 00 00 00 00 00 00 00 00 ; block #4D
        dh 00 00 00 00 00 00 00 00 E5 E6 E5 E6 00 00 00 00 ; block #4E
        dh E7 E8 E7 E8 00 00 00 00 00 00 00 00 00 00 00 00 ; block #4F
        dh 00 00 00 00 00 00 00 00 E7 E8 E7 E8 00 00 00 00 ; block #50
        dh 73 75 F2 F3 00 00 EB EC 00 00 E9 EA 00 00 EB EC ; block #51
        dh F2 F3 75 73 EB EC 00 00 E9 EA 00 00 EB EC 00 00 ; block #52
        dh 00 00 E9 EA 00 00 EB EC 00 00 E9 EA 00 00 EB EC ; block #53
        dh E9 EA 00 00 EB EC 00 00 E9 EA 00 00 EB EC 00 00 ; block #54
        dh 43 14 15 16 44 18 19 1A 45 1C 1D 1E 46 ED EE 4A ; block #55
        dh 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 46 ED EE 4A ; block #56
        dh 13 14 15 47 17 18 19 48 1B 1C 1D 49 46 ED EE 4A ; block #57
        dh EF 00 00 F1 F0 00 00 00 00 00 00 00 00 00 00 00 ; block #58
        dh A7 A8 A9 AA D4 28 29 2A D5 1C 1D 1E D6 20 21 22 ; block #59
        dh A7 A8 A9 AA 27 28 29 D8 1B 1C 1D D9 1F 20 21 DA ; block #5A
        dh 75 73 73 73 00 00 00 00 00 00 00 00 00 00 00 00 ; block #5B
        dh 73 73 73 75 00 00 00 00 00 00 00 00 00 00 00 00 ; block #5C
        dh 73 76 F2 F3 00 00 EB EC 00 00 E9 EA 00 00 EB EC ; block #5D
        dh F2 F3 75 73 EB EC 00 00 E9 EA 00 00 EB EC 00 00 ; block #5E
        dh 75 73 73 73 00 00 00 00 00 00 00 00 00 00 00 00 ; block #5F
        dh 73 73 73 76 00 00 00 00 00 00 00 00 00 00 00 00 ; block #60
        dh 73 73 73 73 00 00 00 00 00 00 00 00 00 00 00 00 ; block #61
        dh 23 24 25 26 D4 28 29 2A D5 1C 1D 1E D6 20 21 22 ; block #62
        dh 23 24 25 26 27 28 29 D8 1B 1C 1D D9 1F 20 21 DA ; block #63
        dh 00 00 E9 EA 00 00 EB EC 00 00 E9 EA 2B 2C EB EC ; block #64
        dh E9 EA 00 00 EB EC 00 00 E9 EA 00 00 EB EC 2D 2E ; block #65
        dh FC FD FC FD FD FC FD FC FC FD FC FD FD FC FD FC ; block #66
        dh E7 E8 E7 E8 E6 E5 E6 E5 E5 E6 E5 E6 E6 E5 E6 E5 ; block #67
        dh 00 00 00 00 00 00 00 E7 00 00 E7 E6 00 E7 E6 E5 ; block #68
        dh 00 00 00 00 E8 00 00 00 E5 E8 00 00 E6 E5 E8 00 ; block #69
        dh F8 F8 00 00 F8 F8 00 00 F8 F8 00 00 F8 F8 00 00 ; block #6A
        dh FB FB E7 E8 F8 F8 00 00 F8 F8 00 00 F8 F8 00 00 ; block #6B
        dh 00 00 00 00 00 00 00 00 FB FB E7 E8 F8 F8 00 00 ; block #6C
        dh 00 00 F2 F3 00 00 EB EC 00 00 E9 EA 00 00 EB EC ; block #6D
        dh F2 F3 00 00 EB EC 00 00 E9 EA 00 00 EB EC 00 00 ; block #6E
        dh F9 F9 F9 F9 FA FA FA FA FA FA FA FA FA FA FA FA ; block #6F
        dh FA FA FA FA FA FA FA FA FA FA FA FA FA FA FA FA ; block #70
        dh 00 00 00 00 00 00 00 00 00 00 00 00 3F 2C 2D 2E ; block #71
        dh 00 00 00 00 00 00 00 00 00 00 00 00 2B 2C 2D 41 ; block #72
        dh 8D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; block #73
        dh 00 00 00 8E 00 00 00 00 00 00 00 00 00 00 00 00 ; block #74
        dh 8F 91 8F 90 94 89 8C 8B 96 8A 8B 87 92 92 92 92 ; block #75
        dh 8F 91 8F 90 8C 89 8C 8B 86 8A 8B 95 92 92 92 92 ; block #76
        dh 8F 91 8F 90 88 89 88 8B 88 8A 88 96 92 92 92 92 ; block #77
        dh 86 87 86 87 88 88 88 96 88 88 88 96 88 88 88 96 ; block #78
        dh 00 00 00 00 A7 A8 A9 AA 45 1C 1D 1E 46 20 21 22 ; block #79
        dh 00 00 00 00 A7 A8 A9 AA 1B 1C 1D 1E 1F 20 21 22 ; block #7A
        dh 00 00 00 00 A7 A8 A9 AA 1B 1C 1D 49 1F 20 21 4A ; block #7B
        dh FE 00 00 00 A7 A8 A9 AA 1B 1C 1D 1E 1F 20 21 22 ; block #7C
        dh 00 00 00 FF A7 A8 A9 AA 1B 1C 1D 1E 1F 20 21 22 ; block #7D
        dh 00 00 00 00 00 00 00 00 A7 A8 A9 AA 46 20 21 22 ; block #7E
        dh 00 00 00 00 00 00 00 00 A7 A8 A9 AA 1F 20 21 22 ; block #7F
        dh 00 00 00 00 00 00 00 00 A7 A8 A9 AA 1F 20 21 4A ; block #80
        dh 00 00 00 00 FE 00 00 00 A7 A8 A9 AA 1F 20 21 22 ; block #81
        dh 00 00 00 00 00 00 00 FF A7 A8 A9 AA 1F 20 21 22 ; block #82
        dh 00 00 00 00 00 00 00 00 00 00 00 00 A7 A8 A9 AA ; block #83
        dh 00 00 00 00 00 00 00 00 FE 00 00 00 A7 A8 A9 AA ; block #84
        dh 00 00 00 00 00 00 00 00 00 00 00 FF A7 A8 A9 AA ; block #85
        dh 00 35 36 37 00 3A 3B 3C 00 00 00 00 00 00 00 00 ; block #86
        dh 38 39 00 00 3D 3E 00 00 00 00 00 00 00 00 00 00 ; block #87
        dh 00 00 00 00 00 00 35 36 00 00 3A 3B 00 00 00 00 ; block #88
        dh 00 00 00 00 37 38 39 00 3C 3D 3E 00 00 00 00 00 ; block #89
        dh 0F 10 0F 10 11 12 11 12 0F 10 0F 10 11 12 11 12 ; block #8A
        dh 00 0F 10 0F 00 11 12 11 0F 10 0F 10 11 12 11 12 ; block #8B
        dh 10 0F 10 0F 12 11 12 11 0F 10 0F 10 11 12 11 12 ; block #8C
        dh 10 0F 10 00 12 11 12 00 0F 10 0F 10 11 12 11 12 ; block #8D
        dh FA FA FA FA E6 E5 FA FA FA FA FA FA FA FA E6 E5 ; block #8E
        dh F9 F9 F9 F9 E6 E5 FA FA FA FA FA FA FA FA E6 E5 ; block #8F
        dh 00 0F 10 00 00 11 12 00 0F 10 0F 10 11 12 11 12 ; block #90
        dh FB FB E5 E5 F8 F8 00 00 F8 F8 00 00 F8 F8 00 00 ; block #91
        dh F8 F8 00 00 F8 F8 00 00 F8 F8 00 00 F8 F8 2D 2E ; block #92
        dh 73 75 F2 F3 00 00 EB EC 00 00 E9 EA 2B 2C EB EC ; block #93
        dh F2 F3 75 73 EB EC 00 00 E9 EA 00 00 EB EC 2D 2E ; block #94
        dh 00 E1 E2 00 00 E1 E2 00 00 E1 E2 00 2B E1 E2 2E ; block #95
        dh 00 E3 E4 00 00 E3 E4 00 00 E3 E4 00 2F E3 E4 2F ; block #96
        dh 30 33 34 30 00 E1 E2 00 00 E1 E2 00 00 E1 E2 00 ; block #97
        dh 00 00 00 00 00 00 00 00 00 00 00 00 FE 00 00 00 ; block #98
        dh 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF ; block #99
        dh 00 00 00 00 00 00 00 00 F4 F5 F4 F5 F6 F7 F6 F7 ; block #9A
        dh 00 00 00 00 00 00 00 00 00 00 00 F4 00 00 00 F6 ; block #9B
        dh 00 00 00 00 00 00 00 00 F5 00 00 00 F7 00 00 00 ; block #9C
        block 1584, #00         ; padding

objectTable:
        ;  x (b-end)  y  type
        db #00, #1D, 19, #A2    ; x=29 snowOwl
        db #00, #22, 19, #95    ; x=34 sundae
        db #00, #38, 17, #AF    ; x=56 viking
        db #00, #3D, 16, #A4    ; x=61 snowBall
        db #00, #41, 16, #AF    ; x=65 viking
        db #00, #49, 17, #01    ; x=73 shatterbomb
        db #00, #4C, 12, #9E    ; x=76 bullfinch
        db #00, #5C, 18, #A0    ; x=92 bullfinch
        db #00, #65, 12, #9D    ; x=101 bullfinch
        db #00, #71, 20, #A2    ; x=113 snowOwl
        db #00, #75, 20, #92    ; x=117 iceCream
        db #00, #89, 12, #9F    ; x=137 bullfinch
        db #00, #93,  4, #A2    ; x=147 snowOwl
        db #00, #94, 11, #9F    ; x=148 bullfinch
        db #00, #96,  4, #06    ; x=150 coin
        db #00, #98, 20, #A6    ; x=152 santa
        db #00, #AB, 18, #AA    ; x=171 piranha
        db #00, #B2,  7, #B5    ; x=178 cableCar
        db #00, #B5, 18, #AA    ; x=181 piranha
        db #00, #BF, 12, #93    ; x=191 icePop
        db #00, #C2,  4, #06    ; x=194 coin
        db #00, #CD,  7, #B5    ; x=205 cableCar
        db #00, #D4,  8, #97    ; x=212 bullfinch
        db #00, #DB, 16, #94    ; x=219 snowman
        db #00, #E0,  3, #9E    ; x=224 bullfinch
        db #00, #E5, 22, #AA    ; x=229 piranha
        db #00, #F3, 16, #AF    ; x=243 viking
        db #01, #06,  8, #A5    ; x=262 snowBall
        db #01, #0E,  4, #A5    ; x=270 snowBall
        db #01, #26,  8, #05    ; x=294 slimyWorms
        db #01, #2A,  4, #A4    ; x=298 snowBall
        db #01, #31, 20, #92    ; x=305 iceCream
        db #01, #41, 20, #B3    ; x=321 pressPlatform
        db #01, #49, 20, #B4    ; x=329 pressPlatform
        db #01, #55, 16, #02    ; x=341 powerGun
        db #01, #5D,  4, #A2    ; x=349 snowOwl
        db #01, #65, 16, #A2    ; x=357 snowOwl
        db #01, #66,  3, #98    ; x=358 bullfinch
        db #01, #6D, 22, #AA    ; x=365 piranha
        db #01, #75, 12, #AC    ; x=373 penguin
        db #01, #84, 16, #AF    ; x=388 viking
        db #01, #8F, 12, #B0    ; x=399 polarBear
        db #01, #96, 22, #AA    ; x=406 piranha
        db #01, #98, 20, #B4    ; x=408 pressPlatform
        db #01, #AA, 10, #95    ; x=426 sundae
        db #01, #B0, 22, #A9    ; x=432 piranha
        db #01, #BA,  7, #B5    ; x=442 cableCar
        db #01, #C9, 22, #AA    ; x=457 piranha
        db #01, #CA,  7, #B6    ; x=458 cableCar
        db #01, #D9,  7, #B5    ; x=473 cableCar
        db #01, #E9, 16, #06    ; x=489 coin
        db #01, #F0,  4, #94    ; x=496 snowman
        db #01, #F5, 12, #A4    ; x=501 snowBall
        db #02, #01, 20, #92    ; x=513 iceCream
        db #02, #0A, 20, #93    ; x=522 icePop
        db #02, #14, 13, #06    ; x=532 coin
        db #02, #16, 15, #95    ; x=534 sundae
        db #02, #1B,  8, #03    ; x=539 lazerGun
        db #02, #22, 20, #94    ; x=546 snowman
        db #02, #28, 17, #96    ; x=552 pressPlatform
        db #02, #3D, 13, #96    ; x=573 pressPlatform
        db #02, #40,  8, #04    ; x=576 soupCan
        db #02, #46, 16, #AC    ; x=582 penguin
        db #02, #4A, 16, #A4    ; x=586 snowBall
        db #02, #53, 20, #B0    ; x=595 polarBear
        db #02, #65,  9, #96    ; x=613 pressPlatform
        db #02, #69, 20, #01    ; x=617 shatterbomb
        db #02, #70,  4, #A5    ; x=624 snowBall
        db #02, #72,  4, #A5    ; x=626 snowBall
        db #02, #7E, 15, #92    ; x=638 iceCream
        db #02, #89, 13, #B4    ; x=649 pressPlatform
        db #02, #9E,  3, #9E    ; x=670 bullfinch
        db #02, #A8, 20, #B0    ; x=680 polarBear
        db #02, #B9, 20, #A7    ; x=697 inuit
        db #02, #BD, 12, #9D    ; x=701 bullfinch
        db #02, #C1, 20, #05    ; x=705 slimyWorms
        db #02, #D5, 12, #9E    ; x=725 bullfinch
        db #02, #DA, 12, #A4    ; x=730 snowBall
        db #02, #E3, 15, #B3    ; x=739 pressPlatform
        db #02, #EC, 15, #B4    ; x=748 pressPlatform
        db #02, #F5, 16, #06    ; x=757 coin
        db #02, #FA,  6, #9E    ; x=762 bullfinch
        db #03, #00,  8, #A8    ; x=768 inuit
        db #03, #0F, 17, #B3    ; x=783 pressPlatform
        db #03, #12, 20, #B4    ; x=786 pressPlatform
        db #03, #26, 16, #B1    ; x=806 fountain
        db #03, #2E, 22, #A9    ; x=814 piranha
        db #03, #3A, 16, #B1    ; x=826 fountain
        db #03, #49, 22, #AA    ; x=841 piranha
        db #03, #4D,  4, #A8    ; x=845 inuit
        db #03, #4E, 16, #01    ; x=846 shatterbomb
        db #03, #53, 15, #9F    ; x=851 bullfinch
        db #03, #64, 12, #9F    ; x=868 bullfinch
        db #03, #6B,  8, #A8    ; x=875 inuit
        db #03, #78,  4, #B0    ; x=888 polarBear
        db #03, #7D, 11, #B4    ; x=893 pressPlatform
        db #03, #81, 20, #A2    ; x=897 snowOwl
        db #03, #8E,  8, #A8    ; x=910 inuit
        db #03, #A5,  8, #A8    ; x=933 inuit
        db #03, #A8, 16, #B7    ; x=936 iceCube
        db #03, #AC,  7, #A3    ; x=940 snowBall
        db #03, #B4,  7, #A3    ; x=948 snowBall
        db #03, #BB, 16, #B7    ; x=955 iceCube
        db #03, #C4, 17, #96    ; x=964 pressPlatform
        db #03, #DA, 12, #A5    ; x=986 snowBall
        db #03, #E7,  8, #97    ; x=999 bullfinch
        db #03, #ED, 17, #A5    ; x=1005 snowBall
        db #03, #FA, 11, #9E    ; x=1018 bullfinch
        db #03, #FA, 11, #9D    ; x=1018 bullfinch
        db #04, #14,  4, #9D    ; x=1044 bullfinch
        db #04, #19,  8, #A4    ; x=1049 snowBall
        db #04, #21, 22, #AA    ; x=1057 piranha
        db #04, #26, 16, #B2    ; x=1062 fountain
        db #04, #31, 17, #94    ; x=1073 snowman
        db #04, #3A, 16, #B1    ; x=1082 fountain
        db #04, #44,  9, #9E    ; x=1092 bullfinch
        db #04, #49, 22, #AA    ; x=1097 piranha
        db #04, #4E, 16, #B1    ; x=1102 fountain
        db #04, #56, 22, #AA    ; x=1110 piranha
        db #04, #72, 16, #B1    ; x=1138 fountain
        db #04, #7A, 22, #A9    ; x=1146 piranha
        db #04, #7A, 22, #AA    ; x=1146 piranha
        db #04, #90, 20, #9F    ; x=1168 bullfinch
        db #04, #95, 11, #9C    ; x=1173 bullfinch
        db #04, #C0,  8, #AB    ; x=1216 penguin
        db #04, #DA, 12, #92    ; x=1242 iceCream
        db #04, #E2, 20, #04    ; x=1250 soupCan
        db #04, #EB, 20, #94    ; x=1259 snowman
        db #04, #EB, 12, #93    ; x=1259 icePop
        db #04, #EC,  8, #B7    ; x=1260 iceCube
        db #04, #F0, 13, #06    ; x=1264 coin
        db #04, #FE,  8, #06    ; x=1278 coin
        db #05, #04, 20, #09    ; x=1284 burrow
        db #05, #0F,  7, #AD    ; x=1295 icicle
        db #05, #11, 13, #96    ; x=1297 pressPlatform
        db #05, #15,  8, #04    ; x=1301 soupCan
        db #05, #1B, 15, #AD    ; x=1307 icicle
        db #05, #1C,  5, #96    ; x=1308 pressPlatform
        db #05, #25, 20, #95    ; x=1317 sundae
        db #05, #34, 19, #9B    ; x=1332 bullfinch
        db #05, #3C,  5, #96    ; x=1340 pressPlatform
        db #05, #3D,  8, #92    ; x=1341 iceCream
        db #05, #41,  8, #AC    ; x=1345 penguin
        db #05, #45, 17, #96    ; x=1349 pressPlatform
        db #05, #4A, 11, #97    ; x=1354 bullfinch
        db #05, #5E, 12, #95    ; x=1374 sundae
        db #05, #63,  8, #9D    ; x=1379 bullfinch
        db #05, #69, 12, #93    ; x=1385 icePop
        db #05, #6C,  8, #9D    ; x=1388 bullfinch
        db #05, #70,  9, #92    ; x=1392 iceCream
        db #05, #76,  7, #97    ; x=1398 bullfinch
        db #05, #8E, 12, #93    ; x=1422 icePop
        db #05, #8F, 18, #B4    ; x=1423 pressPlatform
        db #05, #98, 17, #92    ; x=1432 iceCream
        db #05, #99,  8, #95    ; x=1433 sundae
        db #05, #A1,  4, #94    ; x=1441 snowman
        db #05, #BA, 16, #B7    ; x=1466 iceCube
        db #05, #C2, 13, #96    ; x=1474 pressPlatform
        db #05, #C5, 20, #94    ; x=1477 snowman
        db #05, #C8, 13, #9E    ; x=1480 bullfinch
        db #05, #CD, 12, #AE    ; x=1485 viking
        db #05, #D8,  8, #A4    ; x=1496 snowBall
        db #05, #D9, 18, #03    ; x=1497 lazerGun
        db #05, #E5, 12, #9E    ; x=1509 bullfinch
        db #05, #EF, 19, #A0    ; x=1519 bullfinch
        db #05, #F8, 19, #A3    ; x=1528 snowBall
        db #06, #04, 19, #AC    ; x=1540 penguin
        db #06, #09, 19, #05    ; x=1545 slimyWorms
        db #06, #0C, 19, #AC    ; x=1548 penguin
        db #06, #14, 19, #AB    ; x=1556 penguin
        db #06, #1B, 20, #AB    ; x=1563 penguin
        db #06, #21, 20, #AB    ; x=1569 penguin
        db #06, #2E, 18, #AB    ; x=1582 penguin
        db #06, #58,  8, #BF    ; x=1624 bossIceCream0
        db #06, #71, 20, #05    ; x=1649 slimyWorms
        db #06, #72, 16, #03    ; x=1650 lazerGun
        db #06, #74,  8, #01    ; x=1652 shatterbomb
        db #06, #7D, 20, #00    ; x=1661 shopMole
        db #06, #7D, 12, #07    ; x=1661 pintaADay
        db #06, #83, 20, #02    ; x=1667 powerGun
        db #7F, #FF             ; stop mark
        block 302, #00          ; padding

; #8A00
blockMap:
        dh 88 28 2A 00 41 05    ;██         ▖;
        dh 89 29 2B 42 43 05    ;██         𜴍;
        dh 28 2A 00 00 41 05    ;██          ;
        dh 29 2B 00 42 43 05    ;██          ;
        dh 00 02 00 74 2E 05    ;██▌  𜺠   ▐  ;
        dh 00 00 30 36 75 05    ;██▌   𜴄𜶀    ;
        dh 00 30 32 34 2D 05    ;██▌     𜴄𜶀  ;
        dh 00 31 33 2F 2D 05    ;██▌     𜵑𜴁  ;
        dh 00 00 31 37 76 05    ;██▌   𜵑𜴁    ;
        dh 00 28 2A 73 2E 05    ;██▌  𜺫      ;
        dh 00 29 2B 00 1F 03    ;██▌         ;
        dh 00 00 28 2A 1F 03    ;██▌         ;
        dh 00 88 29 2B 21 03    ;██𜷀      ▖  ;
        dh 00 89 00 00 1E 03    ;███𜺣     𜴍  ;
        dh 00 00 00 00 18 03    ;███𜷀        ;
        dh 00 00 00 01 05 03    ;████        ;
        dh 00 28 2A 07 12 03    ;████        ;
        dh 00 29 2B 00 06 05    ;██ 𜺫        ;
        dh 00 00 88 42 43 05    ;██     ▖    ;
        dh 00 00 89 74 2E 05    ;██▌  𜺠 𜴍    ;
        dh 00 00 30 36 75 05    ;██▌   𜴄𜶀    ;
        dh 00 30 32 34 2D 05    ;██▌     𜴄𜶀  ;
        dh 00 31 2F 78 77 05    ;██▌     𜵑𜴁  ;
        dh 00 00 31 37 76 05    ;██▌   𜵑𜴁    ;
        dh 00 02 00 73 2E 05    ;██▌  𜺫   ▐  ;
        dh 00 28 2A 00 41 05    ;██          ;
        dh 00 29 2B 00 08 05    ;██          ;
        dh 00 00 88 00 41 05    ;██     ▖    ;
        dh 00 00 89 42 43 05    ;██     𜴍    ;
        dh 00 00 28 2A 00 17    ;█𜵊          ;
        dh 00 00 29 2B 00 18    ;█𜷀          ;
        dh 00 00 6B 6A 92 05    ;██▀▀▀▀▀▜    ;
        dh 00 00 4F 42 43 05    ;██     ▐    ;
        dh 00 4F 91 4D 41 05    ;██   ▐▀▜ ▐  ;
        dh 00 6B 4D 4D 07 05    ;██   ▐ ▐▀▜  ;
        dh 00 4F 00 00 91 05    ;██▀▜     ▐  ;
        dh 00 4F 91 6A 4D 3D    ;██ ▐▀▀▀▜ ▐  ;
        dh 00 6B 4D 00 00 3D    ;██     ▐▀▜  ;
        dh 00 00 00 00 04 05    ;██ 𜺠        ;
        dh 00 00 00 04 11 03    ;████ 𜺠      ;
        dh 00 00 07 11 03 03    ;██████      ;
        dh 00 6D 64 12 49 49    ;██████▄▄▄▄  ;
        dh 00 5F 00 22 40 0D    ;████ 𜺫      ;
        dh 00 61 28 2A 40 0D    ;████        ;
        dh 00 61 29 2B 40 0D    ;████        ;
        dh 00 61 00 00 40 0D    ;████        ;
        dh 00 60 00 23 40 0D    ;████ 𜺠      ;
        dh 00 5E 65 11 48 48    ;██████▀▀▀▀  ;
        dh 00 5D 64 12 0F 0F    ;██████▄▄▄▄  ;
        dh 00 5F 00 22 00 24    ;█𜵂   𜺫      ;
        dh 00 61 00 00 00 24    ;█𜵂          ;
        dh 2A 61 00 00 00 24    ;█𜵂          ;
        dh 2B 61 00 00 00 24    ;█𜵂          ;
        dh 00 60 00 00 00 24    ;█𜵂          ;
        dh 00 5E 54 65 11 0E    ;████▀▀▀▀▀▀  ;
        dh 00 5D 53 64 12 49    ;████▄▄▄▄▄▄  ;
        dh 00 5F 00 00 22 40    ;██ 𜺫        ;
        dh 00 61 00 00 00 40    ;██          ;
        dh 00 61 00 4F 00 40    ;██   ▐      ;
        dh 00 61 00 6B 4D 40    ;██ ▐▀▜      ;
        dh 00 61 00 00 4F 40    ;██ ▐        ;
        dh 00 60 00 23 6B 40    ;██▀▜ 𜺠      ;
        dh 00 6E 65 11 0E 48    ;██████▀▀▀▀  ;
        dh 00 00 9B 05 03 03    ;██████▂     ;
        dh 00 4F 9C 05 03 03    ;██████🮂  ▐  ;
        dh 00 6B 91 05 03 03    ;██████▀▜▀▜  ;
        dh 00 00 4F 17 03 03    ;█████𜵊 ▐    ;
        dh 00 6B 4D 1D 03 03    ;█████𜺨 ▐▀▜  ;
        dh 00 4F 00 20 03 03    ;████𜵊    ▐  ;
        dh 00 00 00 71 05 03    ;████𜺨       ;
        dh 00 00 00 00 17 03    ;███𜵊        ;
        dh 00 00 00 00 1D 03    ;███𜺨        ;
        dh 00 00 4F 00 20 03    ;██𜵊    ▐    ;
        dh 00 6B 4D 00 71 05    ;██𜺨    ▐▀▜  ;
        dh 00 4F 00 00 07 05    ;██       ▐  ;
        dh 00 4F 00 00 01 05    ;██       ▐  ;
        dh 00 6B 4D 00 04 05    ;██ 𜺠   ▐▀▜  ;
        dh 00 00 6B 92 11 03    ;████▀▀▀▜    ;
        dh 00 00 00 9A 12 49    ;█████       ;
        dh 00 00 00 00 22 40    ;██ 𜺫        ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 23 40    ;██ 𜺠        ;
        dh 00 23 6B 92 11 48    ;████▀▀▀▜ 𜺠  ;
        dh 07 11 0E 10 0F 49    ;██████████  ;
        dh 07 12 57 00 23 6F    ; ▐ 𜺠  ████  ;
        dh 00 22 4F 07 11 48    ;████   ▐ 𜺫  ;
        dh 00 00 6B 92 12 49    ;████▀▀▀▜    ;
        dh 00 00 00 00 22 40    ;██ 𜺫        ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 6B 00 40    ;██  ▀▜      ;
        dh 00 00 6B 4D 00 40    ;██   ▐▀▜    ;
        dh 00 6B 4D 00 00 40    ;██     ▐▀▜  ;
        dh 00 4F 91 4D 00 40    ;██   ▐▀▜ ▐  ;
        dh 00 00 00 6B 4F 40    ;██ ▐▀▜      ;
        dh 00 00 00 00 4F 40    ;██ ▐        ;
        dh 00 00 00 04 11 48    ;████ 𜺠      ;
        dh 00 00 07 11 03 03    ;██████      ;
        dh 66 66 66 12 0F 49    ;██████      ;
        dh 00 00 00 22 00 40    ;██   𜺫      ;
        dh 66 66 66 66 66 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 23 00 40    ;██   𜺠      ;
        dh 00 00 9A 13 0E 48    ;███████     ;
        dh 00 6D 53 64 12 49    ;████▄▄▄▄▄▄  ;
        dh 00 5B 00 00 22 40    ;██ 𜺫        ;
        dh 00 47 00 00 72 40    ;██𜺣         ;
        dh 00 47 00 00 1F 4A    ;██▌         ;
        dh 00 47 00 00 71 40    ;██𜺨         ;
        dh 00 47 00 00 72 40    ;██𜺣         ;
        dh 00 47 00 00 1F 4A    ;██▌         ;
        dh 00 47 00 00 04 40    ;██ 𜺠        ;
        dh 00 51 53 64 13 4A    ;████▄▄▄▄▄▄  ;
        dh 00 5B 00 00 06 6F    ; ▐ 𜺫        ;
        dh 00 47 00 00 1F 4A    ;██▌         ;
        dh 00 47 00 00 71 40    ;██𜺨         ;
        dh 00 47 00 00 07 40    ;██          ;
        dh 00 47 00 00 04 40    ;██ 𜺠        ;
        dh 00 47 00 07 11 48    ;████        ;
        dh 00 47 00 07 12 0F    ;████        ;
        dh 00 5C 00 00 22 00    ;   𜺫        ;
        dh 00 6E 65 11 0E 0E    ;██████▀▀▀▀  ;
        dh 00 00 01 05 03 03    ;██████      ;
        dh 0E 0E 0E 03 03 03    ;████████████;
        dh 49 49 49 49 49 03    ;████████████;
        dh 70 70 70 70 70 03    ;██          ;
        dh 48 48 48 48 70 03    ;██  ████████;
        dh 03 03 03 56 70 03    ;██  ████████;
        dh 03 03 03 56 70 03    ;██  ████████;
        dh 03 0F 0F 49 70 03    ;██  ████████;
        dh 56 58 00 8F 70 03    ;██  ▖▜    ██;
        dh 56 00 0E 48 48 03    ;████████  ██;
        dh 56 58 0F 0F 0F 03    ;████████  ██;
        dh 56 00 00 00 00 03    ;██        ██;
        dh 03 0E 0E 55 58 03    ;██  ████████;
        dh 0F 0F 0F 57 00 0F    ;██  ████████;
        dh 66 66 66 66 66 66    ;            ;
        dh 0E 0E 0E 0E 0E 03    ;████████████;
        dh 0F 0F 0F 0F 0F 03    ;████████████;
        dh 00 00 00 00 91 03    ;██▀▜        ;
        dh 0E 10 55 58 00 03    ;██    ██████;
        dh 56 00 56 00 91 03    ;██▀▜  ██  ██;
        dh 56 58 57 58 4D 03    ;██ ▐  ██  ██;
        dh 56 00 91 6A 4D 03    ;██ ▐▀▀▀▜  ██;
        dh 03 0E 55 00 91 03    ;██▀▜  ██████;
        dh 03 0F 0F 55 58 03    ;██  ████████;
        dh 56 58 00 57 00 03    ;██  ██    ██;
        dh 03 55 00 91 6A 03    ;██▀▀▀▜  ████;
        dh 03 57 58 0E 10 57    ;██████  ████;
        dh 56 58 00 56 58 4D    ; ▐  ██    ██;
        dh 03 55 00 57 58 55    ;██  ██  ████;
        dh 03 56 58 91 6A 03    ;██▀▀▀▜  ████;
        dh 0F 56 00 3E 0E 03    ;██████  ████;
        dh 07 12 58 3D 03 03    ;██████  ██  ;
        dh 00 22 00 7C 03 03    ;█████𜵊   𜺫  ;
        dh 00 00 00 81 03 03    ;█████𜺨      ;
        dh 00 00 00 84 03 03    ;████𜵊       ;
        dh 28 2A 00 98 3D 03    ;████𜺨       ;
        dh 29 2B 00 00 7C 03    ;███𜵊        ;
        dh 00 00 00 00 81 03    ;███𜺨        ;
        dh 00 00 28 2A 84 03    ;██𜵊         ;
        dh 00 00 29 2B 98 05    ;██𜺨         ;
        dh 00 6B 6A 4D 07 05    ;██   ▐▀▀▀▜  ;
        dh 00 28 2A 4F 9A 05    ;███  ▐      ;
        dh 00 29 2B 00 07 05    ;██          ;
        dh 00 6B 4F 00 26 05    ;██     ▐▀▜  ;
        dh 00 4F 00 00 07 05    ;██       ▐  ;
        dh 00 4F 02 00 07 05    ;██     ▐ ▐  ;
        dh 00 4F 00 00 07 05    ;██       ▐  ;
        dh 28 2A 00 00 01 05    ;██          ;
        dh 29 2B 00 4F 07 05    ;██   ▐      ;
        dh 00 6B 6A 4D 26 05    ;██   ▐▀▀▀▜  ;
        dh 00 4F 00 00 07 05    ;██       ▐  ;
        dh 00 4F 02 00 08 05    ;██     ▐ ▐  ;
        dh 00 4F 00 00 00 17    ;█𜵊       ▐  ;
        dh 00 00 00 4F 00 18    ;█𜷀   ▐      ;
        dh 00 00 00 6B 92 05    ;██▀▀▀▜      ;
        dh 00 02 00 00 04 05    ;██ 𜺠     ▐  ;
        dh 00 00 00 04 11 03    ;████ 𜺠      ;
        dh 00 00 07 13 0F 03    ;██████      ;
        dh 00 00 00 22 24 05    ;███𜵂 𜺫      ;
        dh 00 28 2A 00 24 12    ;███𜵂        ;
        dh 00 29 2B 00 00 24    ;█𜵂          ;
        dh 00 00 00 00 00 24    ;█𜵂          ;
        dh 28 2A 00 00 24 11    ;███𜵂        ;
        dh 29 2B 00 00 24 05    ;███𜵂        ;
        dh 00 00 00 04 11 03    ;████ 𜺠      ;
        dh 00 00 04 11 03 03    ;██████ 𜺠    ;
        dh 00 07 11 03 03 03    ;████████    ;
        dh 00 26 12 03 03 03    ;████████    ;
        dh 00 00 06 12 0F 49    ;██████ 𜺫    ;
        dh 00 00 00 22 00 40    ;██   𜺫      ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 88 00 00 00 40    ;██       ▖  ;
        dh 00 89 00 00 00 40    ;██       𜴍  ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 28 2A 00 39 40    ;████        ;
        dh 00 29 2B 00 3A 40    ;████        ;
        dh 00 00 00 00 3B 40    ;██▀▀        ;
        dh 00 00 00 00 3C 40    ;██𜶪▌        ;
        dh 28 2A 00 00 00 40    ;██          ;
        dh 29 2B 00 00 39 40    ;████        ;
        dh 00 00 00 00 3A 40    ;████        ;
        dh 00 00 6B 6A 3B 40    ;██▀▀▀▀▀▜    ;
        dh 00 00 4F 00 3C 40    ;██𜶪▌   ▐    ;
        dh 00 6B 4F 00 00 40    ;██     ▐▀▜  ;
        dh 00 4F 00 00 39 40    ;████     ▐  ;
        dh 00 00 00 00 3A 40    ;████        ;
        dh 00 4F 00 00 3B 40    ;██▀▀     ▐  ;
        dh 00 6B 4F 00 3C 40    ;██𜶪▌   ▐▀▜  ;
        dh 00 00 4F 23 00 40    ;██   𜺠 ▐    ;
        dh 00 00 6B 11 0E 48    ;██████▀▜    ;
        dh 00 00 04 05 03 03    ;██████ 𜺠    ;
        dh 00 07 11 03 03 03    ;████████    ;
        dh 00 26 05 03 03 03    ;████████    ;
        dh 00 08 05 03 0F 0F    ;████████    ;
        dh 00 04 05 56 00 23    ; 𜺠  ████ 𜺠  ;
        dh 07 13 0F 57 07 11    ;██  ██████  ;
        dh 00 22 00 50 07 05    ;██  ▐    𜺫  ;
        dh 00 00 23 00 72 05    ;██𜺣    𜺠    ;
        dh 00 07 11 0E 0E 03    ;████████    ;
        dh 00 26 05 03 03 03    ;████████    ;
        dh 00 07 12 03 03 03    ;████████    ;
        dh 00 00 06 05 03 03    ;██████ 𜺫    ;
        dh 00 00 04 05 03 03    ;██████ 𜺠    ;
        dh 00 07 11 03 0F 0F    ;████████    ;
        dh 66 66 05 56 00 4D    ; ▐  ████    ;
        dh 00 07 05 56 00 0E    ;██  ████    ;
        dh 00 26 05 56 00 03    ;██  ████    ;
        dh 00 07 05 56 00 03    ;██  ████    ;
        dh 00 0B 05 56 00 03    ;██  ████    ;
        dh 00 07 05 56 00 03    ;██  ████    ;
        dh 00 0B 05 56 00 03    ;██  ████    ;
        dh 00 26 05 56 00 03    ;██  ████    ;
        dh 00 07 05 56 00 03    ;██  ████    ;
        dh 66 66 12 56 00 03    ;██  ████    ;
        dh 00 00 24 56 00 0F    ;██  ███𜵂    ;
        dh 66 66 11 56 00 00    ;    ████    ;
        dh 00 07 12 03 0E 0E    ;████████    ;
        dh 00 00 06 3D 03 03    ;██████ 𜺫    ;
        dh 00 00 90 3D 03 03    ;███████𜴳    ;
        dh 00 00 00 3D 03 03    ;██████      ;
        dh 00 00 00 7C 03 03    ;█████𜵊      ;
        dh 00 02 00 81 03 03    ;█████𜺨   ▐  ;
        dh 00 00 00 84 03 03    ;████𜵊       ;
        dh 00 88 00 98 3D 03    ;████𜺨    ▖  ;
        dh 00 89 00 00 7C 03    ;███𜵊     𜴍  ;
        dh 00 28 2A 00 7A 03    ;███▌        ;
        dh 00 29 2B 00 81 03    ;███𜺨        ;
        dh 00 00 86 00 7F 03    ;███    𜶖    ;
        dh 00 00 87 00 84 03    ;██𜵊    ▝    ;
        dh 00 00 28 2A 83 03    ;██▌         ;
        dh 00 02 29 2B 98 3D    ;██𜺨      ▐  ;
        dh 00 00 00 00 00 3F    ;██          ;
        dh 66 66 66 66 66 4F    ; ▐          ;
        dh 66 66 66 66 3E 0E    ;████        ;
        dh 66 66 66 3E 03 03    ;██████      ;
        dh 00 00 90 3F 0F 49    ;███████𜴳    ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 39 40    ;████        ;
        dh 00 00 88 00 3A 40    ;████   ▖    ;
        dh 00 00 89 00 3B 40    ;██▀▀   𜴍    ;
        dh 00 88 00 00 3C 40    ;██𜶪▌     ▖  ;
        dh 00 89 00 00 00 40    ;██       𜴍  ;
        dh 00 00 86 00 39 40    ;████   𜶖    ;
        dh 00 00 87 00 3A 40    ;████   ▝    ;
        dh 00 86 00 00 3B 40    ;██▀▀     𜶖  ;
        dh 00 87 00 00 3C 40    ;██𜶪▌     ▝  ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 39 40    ;████        ;
        dh 00 00 02 00 3A 40    ;████   ▐    ;
        dh 00 00 00 00 3B 40    ;██▀▀        ;
        dh 00 00 00 00 3C 40    ;██𜶪▌        ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 02 00 00 00 40    ;██       ▐  ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 00 40    ;██          ;
        dh 00 00 00 00 39 40    ;████        ;
        dh 00 00 02 00 3A 40    ;████   ▐    ;
        dh 00 00 00 00 3B 40    ;██▀▀        ;
        dh 00 88 00 00 3C 40    ;██𜶪▌     ▖  ;
        dh 00 89 00 00 23 40    ;██ 𜺠     𜴍  ;
        dh 00 00 00 07 11 48    ;████        ;
        dh 66 66 66 66 12 03    ;████        ;
        dh 00 00 00 00 22 24    ;█𜵂 𜺫        ;
        dh 00 00 00 00 00 3E    ;██          ;
        dh 96 97 46 46 95 3D    ;██𜴳𜴳𜴳𜴳𜴳𜴳𜴳𜶪  ;
        dh 00 00 00 90 8B 3D    ;███▆█𜴳      ;
        dh 00 00 00 00 8D 5A    ;███🮅        ;
        dh 00 00 00 23 07 40    ;██   𜺠      ;
        dh 00 00 00 22 23 40    ;██ 𜺠 𜺫      ;
        dh 00 00 00 23 22 40    ;██ 𜺫 𜺠      ;
        dh 00 00 23 22 07 40    ;██   𜺫 𜺠    ;
        dh 00 00 22 00 04 40    ;██ 𜺠   𜺫    ;
        dh 00 00 00 24 11 4B    ;█████𜵂      ;
        dh 00 02 00 00 17 03    ;███𜵊     ▐  ;
        dh 00 00 23 00 1D 03    ;███𜺨   𜺠    ;
        dh 00 07 11 00 20 03    ;██𜵊   ██    ;
        dh 00 01 05 00 71 12    ;██𜺨   ██    ;
        dh 00 07 05 55 00 22    ; 𜺫  ████    ;
        dh 00 24 05 03 0E 0E    ;█████████𜵂  ;
        dh 0E 0E 03 03 03 03    ;████████████;
        dh 49 49 49 03 03 03    ;████████████;
        dh 70 70 70 49 49 03    ;██████      ;
        dh 48 48 70 70 70 03    ;██      ████;
        dh 03 03 48 48 70 03    ;██  ████████;
        dh 0F 0F 0F 03 70 03    ;██  ████████;
        dh 00 91 6A 03 70 03    ;██  ██▀▀▀▜  ;
        dh 03 55 58 49 70 03    ;██  ██  ████;
        dh 03 56 58 8F 70 03    ;██  ▖▜  ████;
        dh 03 03 0E 48 48 03    ;████████████;
        dh 0F 0F 0F 0F 03 03    ;████████████;
        dh 00 00 91 6A 0F 03    ;████▀▀▀▜    ;
        dh 55 00 55 58 00 03    ;██    ██  ██;
        dh 56 58 56 58 00 03    ;██    ██  ██;
        dh 56 58 0F 10 10 03    ;████████  ██;
        dh 56 00 00 00 00 03    ;██        ██;
        dh 03 10 55 00 10 03    ;████  ██████;
        dh 56 00 56 58 00 03    ;██    ██  ██;
        dh 56 58 56 6A 6A 03    ;██▀▀▀▀██  ██;
        dh 56 00 57 58 00 03    ;██    ██  ██;
        dh 57 58 91 6A 6A 03    ;██▀▀▀▀▀▜  ██;
        dh 00 91 55 58 00 03    ;██    ██▀▜  ;
        dh 0E 0E 03 0E 0E 03    ;████████████;
        dh 0F 0F 0F 0F 0F 03    ;████████████;
        dh 00 00 91 6A 6A 03    ;██▀▀▀▀▀▜    ;
        dh 0E 10 10 10 00 03    ;██  ████████;
        dh 56 58 91 6A 6A 03    ;██▀▀▀▀▀▜  ██;
        dh 56 00 10 10 10 03    ;████████  ██;
        dh 56 58 91 6A 6A 03    ;██▀▀▀▀▀▜  ██;
        dh 0F 10 10 10 58 03    ;██  ████████;
        dh 00 91 6A 6A 6A 03    ;██▀▀▀▀▀▀▀▜  ;
        dh 0E 0E 0E 0E 0E 03    ;████████████;
        dh 0F 0F 0F 0F 0F 0F    ;████████████;
        dh 00 00 00 00 00 88    ; ▖          ;
        dh 00 00 02 00 00 89    ; 𜴍     ▐    ;
        dh 00 00 00 86 00 00    ;     𜶖      ;
        dh 00 00 00 87 86 09    ;▌  𜶖 ▝      ;
        dh 00 02 00 00 87 0A    ;▌  ▝     ▐  ;
        dh 00 00 00 44 46 45    ;▌▐𜴳𜴳𜴳𜴳      ;
        dh 00 00 88 00 00 0A    ;▌      ▖    ;
        dh 00 00 89 00 00 0C    ;▌      𜴍    ;
        dh 00 00 00 00 00 00    ;            ;
        dh 00 00 00 00 00 02    ; ▐          ;
        dh 00 00 00 00 00 02    ; ▐          ;
        dh 00 00 00 00 00 02    ; ▐          ;
        dh 00 00 00 00 00 4D    ; ▐          ;
        dh 00 00 00 00 00 4D    ; ▐          ;
        dh 00 00 00 86 00 4D    ; ▐   𜶖      ;
        dh 00 00 00 87 00 02    ; ▐   ▝      ;
        dh 00 00 00 00 88 4D    ; ▐ ▖        ;
        dh 00 00 02 00 89 4D    ; ▐ 𜴍   ▐    ;
        dh 00 00 00 00 00 4D    ; ▐          ;
        dh 00 02 00 00 00 00    ;         ▐  ;
        dh 00 00 00 02 00 4D    ; ▐   ▐      ;
        dh 00 00 00 00 00 4D    ; ▐          ;
        dh 03 03 03 03 03 03    ;████████████;
        dh 0F 0F 0F 0F 0F 03    ;████████████;
        dh 00 00 91 6A 6A 03    ;██▀▀▀▀▀▜    ;
        dh 0E 0E 0E 55 00 03    ;██  ████████;
        dh 03 03 03 57 00 03    ;██  ████████;
        dh 03 03 56 00 00 03    ;██    ██████;
        dh 03 03 57 00 00 03    ;██    ██████;
        dh 03 56 00 00 0E 03    ;████    ████;
        dh 0F 57 07 13 03 03    ;██████  ████;
        dh 00 00 00 06 12 03    ;████ 𜺫      ;
        dh 00 00 86 00 06 05    ;██ 𜺫   𜶖    ;
        dh 00 00 87 00 9A 05    ;███    ▝    ;
        dh 00 00 00 74 2E 05    ;██▌  𜺠      ;
        dh 00 00 30 36 75 05    ;██▌   𜴄𜶀    ;
        dh 00 30 32 35 2D 05    ;██▌     𜴄𜶀  ;
        dh 00 31 2F 34 2D 05    ;██▌     𜵑𜴁  ;
        dh 00 00 31 37 76 05    ;██▌   𜵑𜴁    ;
        dh 00 86 00 73 2E 05    ;██▌  𜺫   𜶖  ;
        dh 00 87 00 42 43 05    ;██       ▝  ;
        dh 00 00 88 00 0B 05    ;██     ▖    ;
        dh 00 00 89 42 43 05    ;██     𜴍    ;
        dh 00 00 00 74 2E 05    ;██▌  𜺠      ;
        dh 00 00 30 36 75 05    ;██▌   𜴄𜶀    ;
        dh 00 30 32 34 2D 05    ;██▌     𜴄𜶀  ;
        dh 00 31 35 78 77 05    ;██▌     𜵑𜴁  ;
        dh 00 00 31 37 76 05    ;██▌   𜵑𜴁    ;
        dh 00 00 00 73 2E 05    ;██▌  𜺫      ;
        dh 00 00 00 00 41 05    ;██          ;
        dh 00 86 00 42 43 05    ;██       𜶖  ;
        dh 00 87 00 00 41 05    ;██       ▝  ;
        dh 00 00 88 00 41 05    ;██     ▖    ;
        dh 00 00 89 00 68 05    ;██𜷞𜺣   𜴍    ;
        dh 00 00 00 00 67 05    ;████        ;
        dh 00 00 00 00 69 05    ;██𜴗𜺨        ;
        dh 00 00 00 00 41 12    ;██          ;
        dh 00 00 00 00 00 22    ; 𜺫          ;
        dh 00 00 41 11 0E 0E    ;██████      ;
        dh 00 01 11 03 03 03    ;████████    ;
        dh 0E 0E 03 03 03 03    ;████████████;
        dh 00 00 00 71 12 03    ;████𜺨       ;
        dh 00 28 2A 00 06 05    ;██ 𜺫        ;
        dh 00 29 2B 00 07 05    ;██          ;
        dh 00 00 00 00 68 05    ;██𜷞𜺣        ;
        dh 28 2A 00 00 67 05    ;████        ;
        dh 29 2B 00 00 69 05    ;██𜴗𜺨        ;
        dh 00 00 00 00 04 05    ;██ 𜺠        ;
        dh 00 00 00 72 11 03    ;████𜺣       ;
        dh 0E 0E 0E 0E 03 03    ;████████████;
        dh 03 0F 0F 0F 0F 03    ;████████████;
        dh 03 00 4D 00 4D 03    ;██ ▐   ▐  ██;
        dh 03 00 4D 00 4D 03    ;██ ▐   ▐  ██;
        dh 03 00 91 6A 4D 03    ;██ ▐▀▀▀▜  ██;
        dh 03 00 00 4D 00 03    ;██   ▐    ██;
        dh 0F 00 00 4D 68 03    ;██𜷞𜺣 ▐    ██;
        dh 66 66 66 66 67 03    ;████        ;
        dh 0E 0E 0E 00 69 03    ;██𜴗𜺨  ██████;
        dh 03 03 03 0E 0E 03    ;████████████;


    ENDMODULE
